database:
  host: localhost
  port: 5432
  username: food_app_user
  password: app_password
  databaseName: food_app

# aqueduct db upgrade --connect postgres://food_app_user:app_password@localhost:5432/food_app